name: My first workflow

on: [push,workflow_dispatch]

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: List all files
              run: ls -a
            - name: Checkout repo
              run: actions/checkout@v6
            - name: List all files
              run: ls -a
            - name: Print pwd
              run: pwd
            
 
